/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentHelpRouteImport } from './routes/student.help'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminEnrollmentRouteImport } from './routes/admin.enrollment'
import { Route as AdminCamerasRouteImport } from './routes/admin.cameras'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHelpRoute = StudentHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentRoute = AdminEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCamerasRoute = AdminCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/help': typeof StudentHelpRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/help': typeof StudentHelpRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/help': typeof StudentHelpRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/cameras'
    | '/admin/enrollment'
    | '/admin/health'
    | '/admin/live'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/student/attendance'
    | '/student/help'
    | '/student/profile'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/cameras'
    | '/admin/enrollment'
    | '/admin/health'
    | '/admin/live'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/student/attendance'
    | '/student/help'
    | '/student/profile'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/cameras'
    | '/admin/enrollment'
    | '/admin/health'
    | '/admin/live'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/student/attendance'
    | '/student/help'
    | '/student/profile'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/help': {
      id: '/student/help'
      path: '/help'
      fullPath: '/student/help'
      preLoaderRoute: typeof StudentHelpRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollment': {
      id: '/admin/enrollment'
      path: '/enrollment'
      fullPath: '/admin/enrollment'
      preLoaderRoute: typeof AdminEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cameras': {
      id: '/admin/cameras'
      path: '/cameras'
      fullPath: '/admin/cameras'
      preLoaderRoute: typeof AdminCamerasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCamerasRoute: typeof AdminCamerasRoute
  AdminEnrollmentRoute: typeof AdminEnrollmentRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCamerasRoute: AdminCamerasRoute,
  AdminEnrollmentRoute: AdminEnrollmentRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentHelpRoute: typeof StudentHelpRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentHelpRoute: StudentHelpRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
